FROM maven:3.6.3-openjdk-8
RUN apt-get update
RUN curl -LkvOf https://nodejs.org/dist/v0.10.26/node-v0.10.26-linux-x64.tar.gz
RUN tar --strip-components 1 -xzvf node-v0.10.26-linux-x64.tar.gz -C /usr/local